apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskmanager.fullname" . }}-backend
  labels:
    app: {{ include "taskmanager.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "taskmanager.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "taskmanager.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
