apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.fullname" . }}-client
  labels:
    app: {{ include "taskmanager.fullname" . }}-client
spec:
  selector:
    app: {{ include "taskmanager.fullname" . }}-client
  ports:
    - port: 80
      targetPort: 3000
