apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.fullname" . }}-backend
  labels:
    app: {{ include "taskmanager.fullname" . }}-backend
spec:
  selector:
    app: {{ include "taskmanager.fullname" . }}-backend
  ports:
    - port: 80
      targetPort: 5000
