apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OletiSatishKumar/TaskManager_MERN_Infra.git
    targetRevision: HEAD
    path: helm/charts/taskmanager
    helm:
      valueFiles:
        - ../../environments/prod/prod-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
