name: Update Image Tag and Trigger ArgoCD Sync

on:
  repository_dispatch:
    types: [image-pushed]

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v3

      - name: Update dev-values.yaml with new image tag
        run: |
          sed -i "s|tag:.*|tag: '${{ github.event.client_payload.image_tag }}'|" helm/values/dev-values.yaml

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add helm/values/dev-values.yaml
          git commit -m "Update image tag to ${{ github.event.client_payload.image_tag }}"
          git push
